version: '3.7'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"

    webserver:
        build: .
        restart: always
        depends_on:
            - postgres
            - db
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./data:/home/airflow/data
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    db:
        image: mysql:5.7
        volumes:
            - ./script/dm_covid.sql:/docker-entrypoint-initdb.d/1.sql
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: test123
            MYSQL_DATABASE: dm_covid
            MYSQL_USER: covid
            MYSQL_PASSWORD: covid123

    streamlit:
        build: ./streamlit
        command: "streamlit run src/main.py"
        ports:
            - "8501:8501"
        volumes:
            - "./streamlit/src:/usr/src/app/src"